import Head from "next/head";
import { Box, Button, HStack, Input } from "@chakra-ui/react";
import { ThemeSwitch } from "@/components/theme-switch";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <HStack>
          <Button>Main Button</Button>
          <Button>Secondary Button</Button>
          <Input />
          <Box position="relative">
            <ThemeSwitch />
          </Box>
        </HStack>
      </Box>
    </>
  );
}
